name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 16-ea ]
    name: Java ${{ matrix.java }}
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
      - name: 'Setup Java ${{ matrix.java }}'
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: 'Build with Maven'
        run: |
          mvn --batch-mode --no-transfer-progress verify
      - name: 'Release SNAPSHOT'
        if: github.event_name == 'push' && github.repository == 'forax/panama-fastaccess' && github.ref == 'refs/heads/master'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: SNAPSHOT
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true
          title: "Release SNAPSHOT"
          files: |
            target/*.jar
